### ISSUE TITLE
Multi-currency feature

### ISSUE THREAD

**Issue by Lisoveliy** [solidet-com/steam-currency-converter#4]
Hi, can you add mode feature to show price in other currencies at the same time? Like that for example: 

![image](https://github.com/Solidet-com/steam-currency-converter/assets/56991906/9948bcb6-84a7-42e7-a617-3c3963fa2b6e)

If you can't do that, can you give me a chance to make fork and send you pull request with that feature?

**Comment by Trsnaqe** [comment]
Hello, thank you for the idea. We will discuss it and get back to you. However, my main question concerns the design. Specifically, how would you integrate multiple currencies without compromising the native look that the extension aims for?

**Comment by Lisoveliy** [comment]
One of solutions could be this: 
![image](https://github.com/Solidet-com/steam-currency-converter/assets/56991906/7adb096c-059d-45c2-b081-d5e210b9b5f8)
Or maybe a list showing when you hovering on price.

**Comment by Lisoveliy** [comment]
So in list of lots it could looks like that: 
![image](https://github.com/Solidet-com/steam-currency-converter/assets/56991906/c1ecac78-f41f-40bd-9a15-fb19820806cf)
Well, you get the idea.

**Comment by Trsnaqe** [comment]
Thank you so much for the detailed suggestions with drawn examples, much appreciated. 

I think Augmented Steam's [approach](https://i.imgur.com/aCtJiCf.png) of putting a price table on hover is the most plausible way to do that, but it requires a lot of work for many reasons, such as the need for a settings page to choose currencies to show, a good design that wouldn't stand out and last but not least; not interfering with augmented steam's own table. 

So I would say this is something we can implement in the long term instead of the short term.

Thanks!
