### ISSUE TITLE
Doesn't work on the whishlist page

### ISSUE THREAD

**Issue by th3r1ko** [solidet-com/steam-currency-converter#8]
Greetings! Love your extension! But it doesn't convert currencies on the wishlist page. At least for me. Is this a bug or is it technicaly impossible to implement?

**Comment by Trsnaqe** [comment]
Hi there! I’m glad you’re enjoying the extension. Regarding the wishlist feature, the price selectors for the wishlist, alongside on, thankfully, few parts of the website are defined dynamically via CSS, and they tend to change every few months. Because of this, we’ll need to update our code to accommodate the changes. I’ll work on the adjustments and draft a new release tomorrow. Thanks for bringing this to my attention!

**Comment by Trsnaqe** [comment]
Closing the patch with the latest commit/version. It should go live on the browser stores within a day or two, pending the respective store's review. Thank you for the feedback!

**Comment by th3r1ko** [comment]
Many thanks!
